### ISSUE TITLE
Set up Google Analytics 

### ISSUE THREAD

**Issue by aseoconnor** [galaxypi/galaxy-design#20]
the Galaxy.ooo homepage should be set up with Google Tag Manager, Google Analytics, and Google Optimize. https://analytics.google.com/

This will enable galaxy to track homepage visits over time, test CTAs to get people to engage with the SDK and sign up to the email list, and keep a pulse on growth.

**Comment by guylepage3** [comment]
Moving this to https://github.com/galaxypi/galaxy.ooo

**Comment by guylepage3** [comment]
Moved.. https://github.com/galaxypi/galaxy.ooo/issues/24
