### ISSUE TITLE
UX Copy on the Install

### ISSUE THREAD

**Issue by aseoconnor** [galaxypi/galaxy-design#23]
When installing Galaxy via my terminal I am prompted with this message:
> This script will remove previously installed directories of galaxycli and galaxyd.
> Are you ok with that? (y/N): y
> Continuing with install. Just bear with me for a moment.
> 
> Downloading and installing.... galaxycli and galaxyd.
> #######################################################
> Initializing galaxyd....

I think we could improve this copy and make it more inline with the brand:
> This script will remove previously installed directories of galaxycli and galaxyd.
> Are you ok with that? (y/N): y
> **Preparing for launch. Finalizing prelaunch-operations...**
> 
> Downloading and installing.... galaxycli and galaxyd.
> #######################################################
> Initializing galaxyd....

**Comment by guylepage3** [comment]
Agreed we already have an issue open for this.. on the galaxy repo... I’ll find it in the morning...

**Comment by guylepage3** [comment]
@aseoconnor please take a look at the comments here and would really love your input on the jargon/wording.. https://github.com/galaxypi/galaxy/issues/18

Thank you sir. 👍
